### PR TITLE
feat: Support `source_db_instance_automated_backups_arn` parameter in `restore_to_point_in_time` block

### LINKED ISSUE #397: Add support for restoration of Automated Backups (just one line change)
This parameter was added to the AWS provider in this PR and merged to the main branch on March 15:
https://github.com/hashicorp/terraform-provider-aws/pull/23086

For this to work with the module terraform-aws-modules/terraform-aws-rds, the parameter "source_db_instance_automated_backups_arn" needs to be added to the dynamic block restore_to_point_in_time, like in the example below.

[terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds)/[modules](https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/modules)/[db_instance](https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/modules/db_instance)/main.tf
```
  dynamic "restore_to_point_in_time" {
    for_each = var.restore_to_point_in_time != null ? [var.restore_to_point_in_time] : []

    content {
      restore_time                             = lookup(restore_to_point_in_time.value, "restore_time", null)
      source_db_instance_automated_backups_arn = lookup(restore_to_point_in_time.value, "source_db_instance_automated_backups_arn", null)
      source_db_instance_identifier            = lookup(restore_to_point_in_time.value, "source_db_instance_identifier", null)
      source_dbi_resource_id                   = lookup(restore_to_point_in_time.value, "source_dbi_resource_id", null)
      use_latest_restorable_time               = lookup(restore_to_point_in_time.value, "use_latest_restorable_time", null)
    }
  }
```

This will hugely simplify restoration of backups based on Automated Backups, right now I've been using an external script for that.

### PR DESCRIPTION
**Pull request by comutrex**
## Description
This adds `source_db_instance_automated_backups_arn` parameter to the `restore_to_point_in_time` block in `aws_db_instance` resource.

## Motivation and Context
Ability to use feature added in https://github.com/hashicorp/terraform-provider-aws/pull/23086
Closes #397 

## Breaking Changes
None

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

### CODE REVIEW

**Comment by bryantbiggs** [comment]
we'll need to bump the minimum supported version of the AWS provider for this change as well

**Comment by comutrex** [comment]
@bryantbiggs Provider version looks okay (`>= 4.0`), feature was implemented in `v4.6.0`.

**Comment by bryantbiggs** [comment]
> @bryantbiggs Provider version looks okay (`>= 4.0`), feature was implemented in `v4.6.0`.

It has to be bumped to `>= 4.6.0` because if someone is using anything between 4.0 and 4.5 then it will fail for them

**Comment by comutrex** [comment]
@bryantbiggs AWS provider version bumped.

**Review by bryantbiggs — APPROVED** [review]
Thank you @comutrex !

**Comment by antonbabenko** [comment]
This PR is included in version 4.3.0 :tada:

**Pull request merged**
