### PR TITLE
Use relative links

### PR DESCRIPTION
**Pull request by robinbowes**
Switch to use relative links where possible in the README

### CODE REVIEW

**Comment by antonbabenko** [comment]
This is a bad idea for the Terraform Registry.

**Comment by robinbowes** [comment]
Does it use the same README? It doesn't appear to have updated since you tagged the new version?

**Comment by antonbabenko** [comment]
Yes, it does if you follow the default link - https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/ or [specific version](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/1.0.5)

**Comment by robinbowes** [comment]
Ah, I see - I had assumed my README changes were in the 1.0.5 release - they are not.

OK, I'll close this.

R.

**Pull request closed without merging**
