### PR TITLE
feat: add Windows authentication

### LINKED ISSUE #193: Unable to add Oracle instance to Domain
The following variables are missing for db instance so unable to add instances to AD for Windows authentication

domain - (Optional) The ID of the Directory Service Active Directory domain to create the instance in.
domain_iam_role_name - (Optional, but required if domain is provided) The name of the IAM role to be used when making API calls to the Directory Service.

### PR DESCRIPTION
**Pull request by bryantbiggs**
# Description

- Add Windows authentication per https://www.terraform.io/docs/providers/aws/r/db_instance.html\#domain which is now supported by all RDS engines

closes #193

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@antonbabenko let me know if I can be of help any on this module - quite a few open PRs but no updates since July. I have a few other changes that I will submitting for RDS enhancements now available in the api - thank you!

**Comment by antonbabenko** [comment]
Thanks for this small PR!

Please rebase or merge the master branch in, add outputs for `domain` and `domain_iam_role_name` since they are attributes of `aws_db_instance` resource, and update mssql example to show how this feature is supposed to be used for real.

**Comment by bryantbiggs** [comment]
@antonbabenko - updated the example and validated. Note, it takes about 25 minutes for AWS Directory Service (SimpleAD) to come up and another 15 for RDS, just keep in mind if you plan on running it. We might want to split this out as a standalone example for the AD integration, and the current would stay as it is - just a thought. I had to switch the region to us-east-1 since Directory Service is not available in us-west-x (Ref: [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_SQLServerWinAuth.html)

**Comment by hpAB** [comment]
please can we have this feature merged, mssql rds isnt very useful without auth

**Comment by bryantbiggs** [comment]
@terraform-aws-modules/triage-supporters if anyone gets a chance to review

**Comment by DrFaust92** [comment]
Tested with and without params, LGTM 🚀

**Comment by antonbabenko** [comment]
Thanks all for the work and verification!

[v2.17.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.17.0) has been just released.

**Pull request merged**
