### PR TITLE
feat: Add Intel Enhanced Optimizations for RDS MySQL Example

### PR DESCRIPTION
**Pull request by lucasmelogithub**
## Description
The PR adds an Intel Enhanced Optimizations for RDS MySQL example. The example implements:

- Intel Xeon Instance Selection
- Intel Xeon MySQL Optimizations via an Intel Parameter Group module

Please squash commits if approved/merged. 

## Motivation and Context
New Example

## Breaking Changes
No

## How Has This Been Tested?
- [X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [X] I have executed `pre-commit run -a` on my pull request

Successfully tested deployment:
- TF Plan/Apply
- TF Idempotency(terraform plan/apply a second time)
- Destroy 

image

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thank you for the PR - however, I don't know that this is the appropriate place for this. From what I can tell, this is mostly just using the module that you all have created for the parameter group. The examples we have provided here are demonstrations of the various configurations that this module supports - users are absolutely able to provide their own parameter groups and/or parameter group values, but it doesn't really have any bearing on the examples we've provided. Closing this for now

**Comment by JoshHilliker** [comment]
> thank you for the PR - however, I don't know that this is the appropriate place for this. From what I can tell, this is mostly just using the module that you all have created for the parameter group. The examples we have provided here are demonstrations of the various configurations that this module supports - users are absolutely able to provide their own parameter groups and/or parameter group values, but it doesn't really have any bearing on the examples we've provided. Closing this for now
----------------------
Hi Bryant,  in our example we are showcasing the Intel Optimizations based on our Intel Xeon Tuning Guides.  Our goal was not to show how to utilize parameter groups, but to highlight the specific optimizations/configuration that can increase RDS performance based on Intel Architecture.   We spoke with @antonbabenko at HashiConf & then again at AWS re:Invent about showcasing these value add to customers.    Please let me know if there are additional questions or if a quick meeting would be best.   Thank you  Josh H   cc: @lucasmelogithub

**Comment by antonbabenko** [comment]
@bryantbiggs What you say was also my point to Josh when I met him in October. :) Such examples are not as helpful since users can specify whatever they want in the argument. We know that, and usually, we don't accept such contributions.

On the other hand, let's consider some changes and review it once more if it makes sense to have it here or not. I recommend that the author make this example 100% self-contained without reference to external modules (like [this](https://github.com/intel/terraform-intel-aws-mysql-parameter-group)) and unnecessary logos/images. Include the correct/optimal values for the parameter group as arguments to the module created by this repository - this can be the only interesting part of the example that differentiates it from other similar examples we already have. Leave links to the external repositories/sources, if necessary.

**Comment by antonbabenko** [comment]
I like referring to text documents with or without the code inside. I also don't want us to maintain code where we depend on external repositories we don't control.

@lucasmelogithub @JoshHilliker What do you think? Will you be able to do the change?

**Comment by JoshHilliker** [comment]
> I like referring to text documents with or without the code inside. I also don't want us to maintain code where we depend on external repositories we don't control.
> 
> @lucasmelogithub @JoshHilliker What do you think? Will you be able to do the change?

@antonbabenko  @bryantbiggs - Lucas & I were talking, what are your thoughts about moving the [Intel MySQL parameter group](https://github.com/intel/terraform-intel-aws-mysql-parameter-group/) module into this repo, that way it's managed under the same tree, but we can still use the sub modular approach.

**Comment by antonbabenko** [comment]
I looked into the `Intel MySQL parameter group` module once more, and the **only piece** of code that can be interesting to have in our module is this variable - https://github.com/intel/terraform-intel-aws-mysql-parameter-group/blob/main/variables.tf#L1-L165 .

I don't see a need to make a separate submodule in our repository just for this variable, but instead, I prefer to add a small example or just a markdown file with such values listed. Everyone interested in knowing `how to use this module to deploy RDS resources with an opinionated config provided by Intel` can just look there.

I will let @bryantbiggs decide if he is open to "a small opinionated example" or a "markdown file" (as Bryant mentioned earlier). I am more in favor of a solution that requires less maintenance (=markdown file).

**Comment by JoshHilliker** [comment]
I think what is important as well is the benchmarking and branding of Intel behind these data points in the variables.tf.   We kept this as a separate module to have updates/consumption via git tags w/ the standard tf source version control.    I think having this a separate module with reference to Intel (we can remove image branding) would be of high value to consumers of the module.  We plan to continue to update the module as new Xeon generations land on AWS.  @antonbabenko  @bryantbiggs @lucasmelogithub

**Comment by JoshHilliker** [comment]
@bryantbiggs  @antonbabenko  - Happy New Year!    Love to pick this back up and get your feedback on my latest comment.   Thank You

**Comment by bryantbiggs** [comment]
Hi @JoshHilliker  - so if you wish to keep the module separate and as a standalone module, then I think that we are discussing here is just a markdown file that demonstrates how to use the module with this module plus any other details might need to be aware of and links back to your module/docs.

**Comment by JoshHilliker** [comment]
> Lucas & I talked more. Here's our proposal: 1) removal of Intel branding from Enhanced-Optimization example 2) pull in all parameter group configuration into the stand alone example, so no external dependencies. What do you think?

@antonbabenko  @bryantbiggs

**Comment by bryantbiggs** [comment]
But we (Anton and I, and other contributors) do not have knowledge or experience with these Intel enhanced optimizations - so it doesn't make sense to have code here for that because we will be unable to troubleshoot it. This is why the static markdown is recommended - we can inform users of these configurations and of the module that will do this for them, but we're not testing and validating that

**Comment by JoshHilliker** [comment]
> But we (Anton and I, and other contributors) do not have knowledge or experience with these Intel enhanced optimizations - so it doesn't make sense to have code here for that because we will be unable to troubleshoot it. This is why the static markdown is recommended - we can inform users of these configurations and of the module that will do this for them, but we're not testing and validating that

Okay..  here's my proposal.  we can create an example directory for this and put in the markdown file.   good?

**Comment by antonbabenko** [comment]
@JoshHilliker Yes, please do that, and link to such an example from the main README.md file in the root.

**Comment by lucasmelogithub** [comment]
> @JoshHilliker Yes, please do that, and link to such an example from the main README.md file in the root.

Closing PR. A new one will be created per discussion above.

**Pull request closed without merging**
