### PR TITLE
feat(storage): added support for max_allocated_storage

### PR DESCRIPTION
**Pull request by sekarnaren**
# Description
Adding support for storage autoscaling into Terraform 0.11 branch. 

## Related PR's
https://github.com/terraform-aws-modules/terraform-aws-rds/pull/146

## Related Issues
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/141

### CODE REVIEW

**Comment by robinbowes** [comment]
Please merge this - we need it for TF 0.11.14 :)

**Comment by sekarnaren** [comment]
Awaiting PR review..

**Comment by antonbabenko** [comment]
Thanks @sekarnaren !

[v1.31.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.31.0) has been just released.

**Comment by sekarnaren** [comment]
Thanks @antonbabenko

**Comment by robinbowes** [comment]
Many thanks @antonbabenko

**Pull request merged**
