### PR TITLE
allowing custom parameter_group to pass down the stack

### PR DESCRIPTION
**Pull request by bobchaos**
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/101

### CODE REVIEW

**Comment by antonbabenko** [comment]
Looks good to me.

@jvelasquezjs What do you think?

**Comment by antonbabenko** [comment]
I guess @jvelasquezjs approves this by thumbs-up :)

**Comment by antonbabenko** [comment]
[v1.26.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.26.0) has been released.

**Comment by bobchaos** [comment]
hurray :D

**Pull request merged**
