### PR TITLE
add output for aws_db_instance

### PR DESCRIPTION
**Pull request by SolidSly**
Cf. #114

### CODE REVIEW

**Comment by bishtawi** [comment]
@antonbabenko Any chance we can get this one merged in? I too would like to use `ca_cert_identifier`.

**Comment by bryantbiggs** [comment]
@SolidSly would you mind rebasing to fix merge conflicts when you get a chance?

**Comment by SolidSly** [comment]
Good morning, sorry for the wait @bryantbiggs, I will do it tomorrow.

**Comment by antonbabenko** [comment]
@SolidSly I have just fixed this in 657ec1e and released [v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.7.0).

**Pull request closed without merging**
