### PR TITLE
Fix for issue when MonitoringRoleARN is required

### PR DESCRIPTION
**Pull request by flmmartins**
# Description

This fix issue #136  for terraform 0.12

PS: This has not being tested =( since in my infra I still use 0.11. It would be nice if someone could test

### CODE REVIEW

**Comment by ozbillwang** [comment]
No fix. I still get the error

```
module.db_instance.aws_db_instance.this[0]: Creating...

Error: Error creating DB Instance: InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0.
	status code: 400, request id: aeb9b125-e8fb-4290-a4e3-09d79502e5d7
```

**Comment by ozbillwang** [comment]
ok, seems you didn't set the same as v0.11

This code works:

    monitoring_role_arn = "${var.monitoring_interval > 0 ? coalesce(var.monitoring_role_arn, join("", aws_iam_role.enhanced_monitoring.*.arn)) : "" }"

**Comment by flmmartins** [comment]
I updated the code and added the join. @ozbillwang can you review again?

**Comment by ozbillwang** [comment]
yes, it works with mysql. 

I didn't test with mssql. should be fine.

**Comment by antonbabenko** [comment]
Thanks, @flmmartins !

[v2.12.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.12.0) has been released for Terraform 0.12 users.

**Pull request merged**
