### PR TITLE
fix: Added tflint and fixes in README

### PR DESCRIPTION
**Pull request by Xiaohanxu1996**
## Description
fix some typos in README

## Motivation and Context
To make the document more informational and helpful

## Breaking Changes
No

## How Has This Been Tested?
I have checked the generated README file.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Thanks, @Xiaohanxu1996 !

As you can see I added a few other things to your PR.

[v2.19.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.19.0) has been just released.

**Comment by Xiaohanxu1996** [comment]
Thanks, XD

**Comment by aduewel** [comment]
@antonbabenko @Xiaohanxu1996 why were the aws provider version spec reverted?

**Comment by bryantbiggs** [comment]
hi @aduewel - I'm not sure what you mean by `provider version spec reverted` but this is what the current version specifications are as of today https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/versions.tf

**Comment by aduewel** [comment]
@bryantbiggs sorry for the confusion ... I overlooked the >= (greater than) ... sorry

**Pull request merged**
